path_to_data: 'data/raw/heart_cleveland_upload.csv'
path_to_output: 'models/model.pkl'
path_to_metrics: 'models/val_metrics.json'

splitting_params:
  val_size: 0.33
  random_state: 42

train_params:
  model_type: 'LogisticRegression'

feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_col: 'condition'
  use_scaler: True

