name: CI

on: 
  push:
    branches: [ main, homework1 ]
  pull_request:
    branches: [ main, homework1 ]

jobs:
  linter_and_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd ml_project
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r requirements.txt
        
      - name: Lint with flake8
        run: |
          cd ml_project
          flake8 --max-line-length=127 src
          flake8 --max-line-length=127 tests
          
      - name: Run tests
        run: |
          cd ml_project
          pytest tests